apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
  namespace: jenkins-deploy
  labels:
    app: train-sch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-sch
  template:
    metadata:
      labels:
        app: train-sch
        track: stable
    spec:
      containers:
      - name: train-schedule
        image: goelakshay92/train-schedule:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
