apiVersion: v1
kind: Service
metadata:
  name: train-sch-service
  namespace: jenkins-deploy
spec:
  type: NodePort
  selector:
    app: train-sch
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
